name: shopify_shop_sample
description: "A simple app with integration of shopify"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  shopify_flutter: ^1.5.8
  flutter_dotenv: ^5.1.0
  flutter_inappwebview:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - .env.shopify